#+SETUPFILE: ~/notebook/config/publish/templates/level-3.org
#+TITLE: Create GUIX System Installation using a Debian 12 bootstrap
#+DATE: 2025-12-29
#+AUTHOR: whk (https://whk.name/about/me)
#+EMAIL: develop@whk.name
#+SUBTITLE:
#+DESCRIPTION: 
#+KEYWORDS: guix debian vps
#+STARTUP: content

* Introduction
:documentMetadata:
#+BEGIN_details
#+HTML:<summary>Document Metadata</summary>
+ Copyright:
  - SPDX-License-Identifier: CC-BY-SA-4.0 or AGPL-3.0-or-later
  - SPDX-FileCopyrightText: © 2025 WHK <develop@whk.name>
  - See {{{insertRelativeLink(about/licensing/,Licensing)}}} for more details
+ Author: {{{author}}}
+ Created: {{{date}}}
+ Changes
  - 2025-02-27: Created
  - 2025-12-28: Clean start using 1.5.0rc1 for testing
#+END_details
:END:

Starting with a Debian 12 installation use a [[https://guix.gnu.org/manual/en/html_node/Binary-Installation.html][GNU Guix Binary Installation]]
to create a new Guix system install on the same machine.

This is primarily used on cloud providers who do not provide a Guix installation
image but do provide a Debian one.

Assumptions:
  - VPS provider who does not support Guix natively
  - VPS provides supports virtual console access
  - VPS provides a Debian install image


* Initial Setup

Starting with a default VPS provided Debian 12 configuration do minimal
configuration to allow access.

** VPS Config
This was tested using an incognet.io vps with the following configuration

#+ATTR_HTML: :border 2 :rules all :frame border
|             | Type             | Value              |
|-------------+------------------+--------------------|
| CPU         | AMD Epcy vCPU    | 2                  |
| RAM         | DDR ECC          | 4GB                |
| Disk        |                  | 40GB               |
| OS          | debian-12-x86_64 |                    |
| IP          | IPV4             | 23.137.255.21      |
| Hostname    |                  | uman001.erpetu.net |
| Reverse DNS |                  | Set                |
** Root Authentication Credentials
- SSH key that is set to allow root SSH login to Debian host
  - [[../../config/ssh-identities/index.org::*2025][SSH Identities - 2025/id-2025-development-ed25519]]
- Password set to allow root VNC console access
  - Password manager entry: ~uman001.erpetu.net (server) - root~
** Disable SSH Password Authentication

#+begin_src diff
  --- /etc/ssh/sshd_config.orig	2023-06-15 01:44:05.628294089 +0000
  +++ /etc/ssh/sshd_config	2025-02-27 21:40:17.433564843 +0000
  @@ -54,7 +54,7 @@
   #IgnoreRhosts yes
 
   # To disable tunneled clear text passwords, change to no here!
  -#PasswordAuthentication yes
  +PasswordAuthentication no
   #PermitEmptyPasswords no
 
   # Change to yes to enable challenge-response passwords (beware issues with
#+end_src

** Update debian

#+begin_src bash
  # As root...
  apt update
  apt upgrade
  reboot
  # Log back in as root...
  #  and clean up packages to save space
  apt purge
#+end_src

** Final Configuration

#+begin_example
root@uman001:~# uname -a
Linux uman001.erpetu.net 6.1.0-41-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.158-1 (2025-11-09) x86_64 GNU/Linux
root@uman001:~# lscpu
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          48 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   2
  On-line CPU(s) list:    0,1
Vendor ID:                AuthenticAMD
  BIOS Vendor ID:         QEMU
  Model name:             AMD EPYC 7B12 64-Core Processor
    BIOS Model name:      pc-i440fx-8.2  CPU @ 2.0GHz
    BIOS CPU family:      1
    CPU family:           23
    Model:                49
    Thread(s) per core:   1
    Core(s) per socket:   1
    Socket(s):            2
    Stepping:             0
    BogoMIPS:             4491.55
    Flags:                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr ss
                          e sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_kno
                          wn_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer a
                          es xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse
                           3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2
                           smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr
                           wbnoinvd arat npt lbrv nrip_save tsc_scale vmcb_clean flushbyasid pausefilter pfthreshold 
                          v_vmsave_vmload vgif umip rdpid arch_capabilities
Virtualization features:  
  Virtualization:         AMD-V
  Hypervisor vendor:      KVM
  Virtualization type:    full
Caches (sum of all):      
  L1d:                    64 KiB (2 instances)
  L1i:                    64 KiB (2 instances)
  L2:                     1 MiB (2 instances)
  L3:                     512 MiB (2 instances)
NUMA:                     
  NUMA node(s):           1
  NUMA node0 CPU(s):      0,1
Vulnerabilities:          
  Gather data sampling:   Not affected
  Itlb multihit:          Not affected
  L1tf:                   Not affected
  Mds:                    Not affected
  Meltdown:               Not affected
  Mmio stale data:        Not affected
  Reg file data sampling: Not affected
  Retbleed:               Mitigation; untrained return thunk; SMT disabled
  Spec rstack overflow:   Mitigation; SMT disabled
  Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP disabled; RSB filling; PBRSB-eIBRS Not affe
                          cted; BHI Not affected
  Srbds:                  Not affected
  Tsx async abort:        Not affected

root@uman001:~# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
vda    254:0    0  40G  0 disk 
└─vda1 254:1    0  40G  0 part /

root@uman001:~# df
Filesystem     1K-blocks    Used Available Use% Mounted on
udev             1981404       0   1981404   0% /dev
tmpfs             400916     472    400444   1% /run
/dev/vda1       41169292 1798424  37257496   5% /
tmpfs            2004576       0   2004576   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs             400912       0    400912   0% /run/user/0
#+end_example



* Guix Binary Installation on Debian

This could be done later but I wanted to have an idea of how big the
Debian partition needs to be before resizing.

** Guix 1.5.0rc1 self-contained tarball
- Since this is testing for the release I will use ~guix-install.sh~.
  Generally I prefer not to use it since it doesn't have
  a way to verify its authenticity using gpg and I don't feel like doing
  a manual review each time.
  This appears to be a deliberate choice by the maintainers ([[https://issues.guix.gnu.org/34125][Installation script needs to be secured with a gpg signature]])
- Retrieve binary installation
  #+begin_src bash
    mkdir /root/guix
    cd /root/guix

    # Install git to get signing keys
    apt install git

    # Retrieve the keyring branch for the guix project
    git clone -b keyring https://git.guix.gnu.org/guix.git guix-keyring

    # Pull them into a private gpg keyring
    mkdir gpg
    gpg --homedir /root/guix/gpg --import guix-keyring/*.key

    # Download installation script
    curl --remote-name https://guix.gnu.org/guix-install.sh

    # Download 
    curl --remote-name https://files.ditigal.xyz/guix-release-1.5.0rc1-mirror/guix-binary-1.5.0rc1.x86_64-linux.tar.xz
    curl --remote-name https://files.ditigal.xyz/guix-release-1.5.0rc1-mirror/guix-binary-1.5.0rc1.x86_64-linux.tar.xz.sig

    # Verify the hash matches the anouncement
    sha256sum guix-binary-1.5.0rc1.x86_64-linux.tar.xz
    # 831e22ddf3c5d8b92355abd5af1ad51514f93507c58757afc18bda62006c7f79  guix-binary-1.5.0rc1.x86_64-linux.tar.xz

    # Verify that Rutherther signed the copy of the file retrieved from website
    gpg --homedir /root/guix/gpg --verify guix-binary-1.5.0rc1.x86_64-linux.tar.xz.sig guix-binary-1.5.0rc1.x86_64-linux.tar.xz
     # gpg: WARNING: unsafe permissions on homedir '/root/guix/gpg'
     # gpg: Signature made Fri 26 Dec 2025 01:22:50 PM EST
     # gpg:                using RSA key 6B51071A0FB152ADED9363600322798269E471C3
     # gpg: Good signature from "Rutherther <rutherther@protonmail.com>" [unknown]
     # gpg:                 aka "Rutherther <rutherther@ditigal.xyz>" [unknown]
     # gpg: WARNING: This key is not certified with a trusted signature!
     # gpg:          There is no indication that the signature belongs to the owner.
     # Primary key fingerprint: 3AC5 5D0E 1DA7 AF44 3868  11EE 213D C372 0E7A 023C
     #      Subkey fingerprint: 6B51 071A 0FB1 52AD ED93  6360 0322 7982 69E4 71C3
  #+end_src
- Install using installation script
  #+begin_src bash -n -r
    #  newgidmap is required (ref:newgidmap-required)
    apt install uidmap

    # Run install script using downloaded file
    chmod a+x guix-install.sh
    GUIX_BINARY_FILE_NAME=/root/guix/guix-binary-1.5.0rc1.x86_64-linux.tar.xz /root/guix/guix-install.sh
    # Questions asked during install:
    #  n -  Install AppArmor profile that might be required to run guix-daemon? [Y/n]
    #  n -  Would you like the Guix daemon to automatically discover substitute servers on the local network? [Y/n]
    #  y - Permit downloading pre-built package binaries from the project's build farms? [Y/n]
    #  y - Customize users Bash shell prompt for Guix? [Y/n]
  #+end_src
  - [[(newgidmap-required)]] The install fails with ~[1766945516.749]: [ FAIL ] Missing commands: newgidmap.~
    which is provided by the uidmap package^{[[ref-04]]}
  #+begin_example
	░░░                                     ░░░
	░░▒▒░░░░░░░░░               ░░░░░░░░░▒▒░░
	 ░░▒▒▒▒▒░░░░░░░           ░░░░░░░▒▒▒▒▒░
	     ░▒▒▒░░▒▒▒▒▒         ░░░░░░░▒▒░
		   ░▒▒▒▒░       ░░░░░░
		    ▒▒▒▒▒      ░░░░░░
		     ▒▒▒▒▒     ░░░░░
		     ░▒▒▒▒▒   ░░░░░
		      ▒▒▒▒▒   ░░░░░
		       ▒▒▒▒▒ ░░░░░
		       ░▒▒▒▒▒░░░░░
			▒▒▒▒▒▒░░░
			 ▒▒▒▒▒▒░
	 _____ _   _ _    _    _____       _
	/ ____| \ | | |  | |  / ____|     (_)
       | |  __|  \| | |  | | | |  __ _   _ ___  __
       | | |_ | . ' | |  | | | | |_ | | | | \ \/ /
       | |__| | |\  | |__| | | |__| | |_| | |>  <
	\_____|_| \_|\____/   \_____|\__,_|_/_/\_\

    https://www.gnu.org/software/guix/
    This script installs GNU Guix on your system
    To uninstall, pass in the '--uninstall' parameter.
    Press return to continue...
    [1767105232.137]: Starting installation (Tue Dec 30 09:33:52 AM EST 2025)
    [1767105232.152]: [ INFO ] init system is: systemd
    [1767105232.154]: [ PASS ] verification of required commands completed
    [1767105232.160]: [ WARN ] We recommend installing and/or starting your distribution 'nscd' service
    [1767105232.161]: [ WARN ] Please read 'info guix "Application Setup"' about "Name Service Switch"
    [1767105232.162]: [ INFO ] system is x86_64-linux
    [1767105232.164]: [ INFO ] Using manually provided binary /root/guix/guix-binary-1.5.0rc1.x86_64-linux.tar.xz
    [1767105232.166]: [ INFO ] Installing /var/guix and /gnu...
    [1767105243.429]: [ INFO ] Linking the root user's profile
    [1767105243.432]: [ PASS ] activated root profile at /root/.config/guix/current
    [1767105243.434]: [ INFO ] group kvm exists and build users will be added to it
    [1767105243.436]: [ INFO ] installing guix-daemon to run as an unprivileged user
    [1767105243.458]: [ PASS ] group guix-daemon created
    [1767105243.480]: [ PASS ] user added <guix-daemon>
    [1767105243.483]: [ INFO ] allowing kvm mapping (GID 104) for unprivileged guix-daemon
    Install AppArmor profile that might be required to run guix-daemon? [Y/n]N
    Created symlink /etc/systemd/system/multi-user.target.wants/guix-daemon.service → /etc/systemd/system/guix-daemon.service.
    Would you like the Guix daemon to automatically discover substitute servers on the local network? [Y/n]n
    Created symlink /etc/systemd/system/multi-user.target.wants/gnu-store.mount → /etc/systemd/system/gnu-store.mount.
    [1767105367.617]: [ PASS ] enabled Guix daemon via systemd
    [1767105367.618]: [ INFO ] making the guix command available to other users
    Permit downloading pre-built package binaries from the project's build farms? [Y/n]y
    [1767105407.056]: [ PASS ] Authorized public key for bordeaux.guix.gnu.org
    [1767105407.145]: [ PASS ] Authorized public key for ci.guix.gnu.org
    [1767105407.154]: [ PASS ] installed shell completion
    Customize users Bash shell prompt for Guix? [Y/n]y
    [1767105437.673]: [ PASS ] Bash shell prompt successfully customized for Guix
    [1767105437.674]: [ INFO ] cleaning up /tmp/guix.SntcDX
    [1767105437.676]: [ PASS ] Guix has successfully been installed!
    [1767105437.677]: [ INFO ] Run 'info guix' to read the manual.
    [1767105437.678]: [ INFO ] Please log out and back in to complete the installation.
  #+end_example

** Using apt (Obsolete)
As of 2025-12-13 this method appears to be obsolete due to the
difficultly of backporting security patches into the debian distros
release of GUIX.^{[[ref-05]]}

#+begin_src bash
  apt install guix
  #...
  #The following additional packages will be installed:
  #  fontconfig-config fonts-dejavu-core guile-3.0 guile-3.0-libs guile-bytestructures guile-gcrypt guile-git
  #  guile-gnutls guile-json guile-lzlib guile-sqlite3 guile-ssh guile-zlib libabsl20220623 libaom3 libavif15
  #  libc-dev-bin libc-devtools libc6-dev libcrypt-dev libdav1d6 libde265-0 libdeflate0 libfontconfig1 libgav1-1
  #  libgc1 libgcrypt20-dev libgd3 libgit2-1.5 libgit2-dev libgpg-error-dev libguile-ssh14 libheif1 libhttp-parser-dev
  #  libhttp-parser2.9 libjbig0 libjpeg62-turbo liblerc4 liblz-dev liblz1 libmbedcrypto7 libmbedtls-dev libmbedtls14
  #  libmbedx509-1 libnsl-dev libpcre2-16-0 libpcre2-32-0 libpcre2-dev libpcre2-posix3 librav1e0 libsqlite3-dev
  #  libssh-4 libssh-dev libssh2-1-dev libssl-dev libsvtav1enc1 libtiff6 libtirpc-dev libwebp7 libx265-199 libxpm4
  #  libyuv0 linux-libc-dev manpages-dev nscd rpcsvc-proto zlib1g-dev
  #Suggested packages:
  #  guile-3.0-doc glibc-doc libgcrypt20-doc libgd-tools libmbedtls-doc sqlite3-doc libssh-doc libssl-doc
  #The following NEW packages will be installed:
  #  fontconfig-config fonts-dejavu-core guile-3.0 guile-3.0-libs guile-bytestructures guile-gcrypt guile-git
  #  guile-gnutls guile-json guile-lzlib guile-sqlite3 guile-ssh guile-zlib guix libabsl20220623 libaom3 libavif15
  #  libc-dev-bin libc-devtools libc6-dev libcrypt-dev libdav1d6 libde265-0 libdeflate0 libfontconfig1 libgav1-1
  #  libgc1 libgcrypt20-dev libgd3 libgit2-1.5 libgit2-dev libgpg-error-dev libguile-ssh14 libheif1 libhttp-parser-dev
  #  libhttp-parser2.9 libjbig0 libjpeg62-turbo liblerc4 liblz-dev liblz1 libmbedcrypto7 libmbedtls-dev libmbedtls14
  #  libmbedx509-1 libnsl-dev libpcre2-16-0 libpcre2-32-0 libpcre2-dev libpcre2-posix3 librav1e0 libsqlite3-dev
  #  libssh-4 libssh-dev libssh2-1-dev libssl-dev libsvtav1enc1 libtiff6 libtirpc-dev libwebp7 libx265-199 libxpm4
  #  libyuv0 linux-libc-dev manpages-dev nscd rpcsvc-proto zlib1g-dev
  #0 upgraded, 68 newly installed, 0 to remove and 0 not upgraded.
  #Need to get 83.7 MB of archives.
  #After this operation, 524 MB of additional disk space will be used.
  #Do you want to continue? [Y/n] Y
#+end_src



* Partition Shuffle
If the VPS does not provide for additional disks to be attached and
mounted then resize/repartion the existing system disk to replace
Debian with Guix.

Assumptions:
  - VPS does not allow (de/a)ttachement of disk images
  - VPS provides some form of recovery console to allow disk
    to be repartitioned

Risks:
  - Messing with the boot/system disk partitions can result in
    a unbootable system.

** Resize and Move Debian partition to end of disk
Using the VPS Rescue Mode resize existing partition to prepare for dual boot.
- Assumptions:
  - Debian install references it's disk via UUID vs /dev/... path
  - VPS support booting via a grub boot partition
- Enable and Boot rescue mode
- Shrink Debian Partition
  - *WARNING*: This section can cause an unbootable system
    if you don't understand what it is doing and blindly repeat the commands.

  #+begin_src bash
    # Verify block devices are as expected
    # vda - rescue environment
    # vdb - 40G disk
    lsblk

    # Verify the Debian Partition is currently clean
    e2fsck -f /dev/vdb1

    # Resize Debian ext4 filesystem down to 18G
    resize2fs /dev/vdb1 18G
    # resize2fs 1.47.0 (5-Feb-2023)
    #  Resizing the filesystem /dev/vdb1 to 4718592 (4k) blocks
    #  The filesystem on /dev/vdb1 is now 4718592 (4k) blocks long.

    # Resize the Debian partition down to 18G
    fdisk /dev/vdb
    # p
    #    ...
    #    Device      Start        End  Sectors Size Type
    #    /dev/vdb1    2048   83886044 83883997  40G Linux filesystem
    # d      # Delete the single partition
    # n      # Create a partition
    # Partion number (1-128, default 1): 1
    # First sector (34-83886046), default 2048): 2048
    # Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-83886046, default 83884031): +18G
    #     Created a new partition 1 of type 'Linux filesystem' and of size 18 GiB.
    #     Partion #1 contains a ext4 signature.
    #
    # Do you want to remove the signature? [Y]es/[N]o: N
    # p
    #    ...
    #    Device      Start        End  Sectors Size Type
    #    /dev/vdb1    2048   37750783 37748736  18G Linux filesystem
    #
    #
    # (Sanity Check) Verify Size
    #  fdisk: 512B per sector
    #  resize2fs: 4kB per block 
    #  fdisk: 37748736(sectors) / 8(sectors/blocks) = 4718592(blocks) : resize2fs
    # w  # Write the changes and quit

    # verify partion is still clean
    e2fsck -f /dev/vdb1

    # Exit rescue mode and verify we can still boot debian
    shutdown -h now
  #+end_src

- Move Debian Partition to end of disk
  
  Final Configuration will have 3 partitions - 
    ~bios_boot~, ~/boot~ (guixBoot), and ~/~ (guixRoot)
  so make Debian partition number 4 since it will be deleted later
  and guixRoot will be extended to the end of disk.

  - *WARNING*: This section can cause an unbootable system
    if you don't understand what it is doing and blindly repeat the commands.

  - Sector Calculation
    #+ATTR_HTML: :border 2 :rules all :frame border
    | lastSector     | original ~fdisk p~ for vdb1            | 83886046 | pSector |
    | partitionSizeS | after resize ~fdisk p~ for vdb1        | 37748736 | sector  |
    | firstSector    | lastSector - partitionSize + 1         | 46137311 | pSector |
    | sectorSize     | from ~fdisk~ vdb                       |      512 | byte    |
    | blockSize      | from ~resize2fs~ for vdb1              |     4096 | byte    |
    | partitionSizeB | partitonSizeS * sectorSize / blockSize |  4718592 | blocks  |
    #+TBLFM: @3$3=@1$3 - @2$3 + 1::@6$3=@2$3*@4$3/@5$3

  - Create partition at end matching partition 1s size.
    #+begin_src bash
      fdisk /dev/vdb
      # n
      # Partiton Number: 4
      # First Sector: 46137311
      # Last Sector: 83886046
      # p   # Verify vdb1 and vdb2 Sectors is the same
      # w   # write the changes and quit
    #+end_src

  - Move the debian install from vdb1 to vdb4

    #+begin_src bash
      # Copy the data
      dd if=/dev/vdb1 of=/dev/vdb4 bs=4096 count=4718592 status=progress

      # Verify that the new partition looks correct
      blkid                # vdb1 and vdb4 should be identical except for PARTUUID
      e2fsck -f /dev/vdb4  # should come back clean

      # Remove vdb1 partition entry but do not overwrite data yet
      fdisk /dev/vdb
      # p
      # d
      # Partition number: 1
      # p   # only /dev/vdb4 should be left
      # w   # write table and quit
    #+end_src

** Create a bios boot partition so we can dual boot later if desired

- Disable rescue mode and using ~grub rescue~ boot Debian
  
  The boot will fail with a partition failure and start ~grub rescue~
  automatically

  #+begin_src bash
    # Point to the new Debian partition
    set prefix=(hd0,gpt4)/boot/grub
    set root=hd0,gpt4
    # Boot normally
    insmod normal
    normal
  #+end_src
  
- Create Bios Boot partition and update grub
  #+begin_src bash
    fdisk /dev/vda
    # p
    # n
    # Partition number (1): default
    # First Sector (2048): default
    # Last sector: +32M
    #    Created a new partition 1 of type 'Linux filesystem' and of size 32 MiB
    #    Partition #1 contains a ext4 signature
    # Do you want to remove the signature?  Y     # Don't need old install
    # t    # Change partition type
    # Partition number: 1
    # Partition type: bios_boot   # Alias for #4 BIOS boot 21686148-6449-6E6F-744E-656564454649
    # p
    # w

    # Reinstall grub
    grub-install /dev/vda
  #+end_src
- Reboot and Verify that Debian boots correctly  

** Create and format remaining partitions
#+begin_src bash
    fdisk /dev/vda
    #  # Future /boot Partion
    #  n
    #  default partiton number (2)
    #  default First Sector (67584)
    #  Last sector: +2G
    #
    #  # Future / (GUIX System partition)
    #  n
    #  default partition number (3)
    #  default First Sector (4261888)
    #  default Last Sector (46137310)
    #
    #  p
    #   Disk /dev/vda: 40 GiB, 42949672960 bytes, 83886080 sectors
    #   Units: sectors of 1 * 512 = 512 bytes
    #   Sector size (logical/physical): 512 bytes / 512 bytes
    #   I/O size (minimum/optimal): 512 bytes / 512 bytes
    #   Disklabel type: gpt
    #   Disk identifier: A6061F2A-27A6-423F-B8E9-77CF41A2180C
    #
    #   Device        Start      End  Sectors Size Type
    #   /dev/vda1      2048    67583    65536  32M BIOS boot
    #   /dev/vda2     67584  4261887  4194304   2G Linux filesystem
    #   /dev/vda3   4261888 46137310 41875423  20G Linux filesystem
    #   /dev/vda4  46137311 83886046 37748736  18G Linux filesystem
    #
    #  w

    # Wipe any remaining data from the partitions
    dd if=/dev/zero of=/dev/vda2 bs=4096 status=progress
    dd if=/dev/zero of=/dev/vda3 bs=4096 status=progress

    mke2fs -t ext4 -b 4096 -L "guixBoot" /dev/vda2
    mke2fs -t ext4 -b 4096 -L "guixRoot" /dev/vda3
#+end_src

* Guix System Installation on separate partitions
** guix-minimal-config.scm
A bare bones configuration with outbound networking

*** Base configuration
#+NAME: guix-minimal-config.scm
#+HEADER: :tangle   "tangle/guix-minimal-config.scm"
#+HEADER: :noweb    no-export
#+HEADER: :comments both
#+HEADER: :mkdirp   yes
#+begin_src scheme

  ;; This is an operating system configuration template
  ;; for a "bare bones" setup, with ...
  ;;   no X11 display server.
  ;;   netfilter set to block all incoming except port 22
  ;;   ssh enabled with password login disabled and root key set

  (use-modules (gnu)
	       (guix)
	       (gnu services sysctl)
	       (gnu packages version-control)     ;; for git
	       (gnu packages admin)               ;; for netcat
	       (gnu packages package-management))
  (use-service-modules networking
		       ssh
		       virtualization)            ;; for qemu-guest-agent-service-type

  (operating-system

   ;;
   ;; Hardware specific settings
   ;;
   «vps-required-config»

   ;; Bootloader 
   «dual-boot-bootloader-configuration»

   ;; file systems to mount
   (file-systems
    (cons*
     (file-system
      (device (file-system-label "guixRoot"))
      (mount-point "/")
      (type "ext4"))
     (file-system
      (device (file-system-label "guixBoot"))
      (mount-point "/boot")
      (type "ext4"))
     %base-file-systems))

   ;;
   ;; System specific settings
   ;;
   (host-name "uman001")

   ;;
   ;; General settings that are the same for
   ;; my minimal systems
   ;; 
   (locale "en_US.utf8")
   (timezone "UTC")
   (keyboard-layout (keyboard-layout "us"))

   ;; The "root" account is implicit, and is initially created with the
   ;; empty password.
   (users (cons* %base-user-accounts))

   ;; Packages installed system-wide.  Users can also install packages
   ;; under their own account: use 'guix search KEYWORD' to search
   ;; for packages and 'guix install PACKAGE' to install a package.
   ;;(packages (cons* %base-packages))
   (packages (append (list git netcat nmap tcpdump) %base-packages))

   ;; Add services to the baseline
   (services
    (append
     (list
      «network-configuration-service»
      «nftables-service-type»
      ;; enable guest agent
      ;; Not sure if I want this yet so commented out
      ;; but maybe reenabled.
      ;;(service qemu-guest-agent-service-type)
      «openssh-service-type»)
     (modify-services
      %base-services
      (sysctl-service-type
       config =>
       (sysctl-configuration
	(settings (append
		   «network-configuration-sysctl»
		   %default-sysctl-settings))))
      «guix-service»))))
#+end_src

*** «vps-required-config»
Fix a couple of issues specific to running inside of the VPS
#+begin_src scheme :noweb-ref vps-required-config 
  ;; Fix vnc console terminal issues.
  ;;  Issue: VNC Console was blank
  (kernel-arguments (list "nomodeset")) 
  ;; Allow guix to see virtual disk
  (initrd-modules
   (cons "virtio_scsi"    ;needed to find the disk
	 %base-initrd-modules))
#+end_src
*** «dual-boot-bootloader-configuration»
Configure GRUB to boot Guix by default but also add an entry to
boot the VPS provided Debian so I can switch back and forth during
testing and recovery efforts.
#+begin_src scheme :noweb-ref dual-boot-bootloader-configuration
  (bootloader
   (bootloader-configuration
    (bootloader grub-bootloader)    
    (targets '("/dev/vda"))
    (menu-entries                 ;; Add additional boot entries
     (list
      (menu-entry                 ;; VPS Debian 12 - values taken from 
       (label "debian")           ;; its grub.cfg
       (linux "/boot/vmlinuz-6.1.0-41-amd64")
       (linux-arguments
	'("root=UUID=9a4a0c40-862e-45a3-8c13-e732e6e052e0 ro net.ifnames=0 biosdevname=0 quiet"))
       (initrd "/boot/initrd.img-6.1.0-41-amd64"))))))
#+end_src

*** «network-configuration-service» and «network-configuration-sysctl»
Due to [[*TCP issues - 2025-12][TCP issues - 2025-12]] I cannot just use dhcp to get my network settings
from the VPS.  I am still vacilating between three different configurations
so documenting them here and switching between them for testing.

- «network-configuration-service»
  #+begin_src scheme :noweb-ref network-configuration-service :noweb no-export
  ;; Use dhcpd for network information
  ;;(service dhcpcd-service-type)
  (service static-networking-service-type
	   (list (static-networking
		  (addresses (list 
			      (network-address
			       (device "eth0")
			       (value "23.137.255.21/24"))
			      (network-address
			       (device "eth0")
			       (value "2602:fc24:18:ada7:0000:0000:0000:0001/64"))
			      ))
		  (routes (list
			   (network-route
			    (destination "default")
			    (gateway "23.137.255.1"))
			   ;;       (network-route
			   ;;        (destination "2602:fc24:18::/48")
			   ;;        (device "eth0"))
			   ;;       (network-route
			   ;;        (destination "default")
			   ;;        (gateway "2602:fc24:18::1"))
			   ))
		  ;; (ref:cloudflare-dns-servers)
		  (name-servers '("1.1.1.1"
				  "2606:4700:4700::1111"
				  "1.0.0.1"
				  "2606:4700:4700::1001"))))) 

#+end_src
  - [[(cloudflare-dns-servers)]]: The current public unfiltered [[https://developers.cloudflare.com/1.1.1.1/infrastructure/network-operators/][cloudflare dns servers]].
- «network-configuration-sysctl»
  #+begin_src scheme :noweb-ref network-configuration-sysctl :noweb noexport
	      ;; Disable ipv6 ra 
    ;;          '(("net.ipv6.conf.all.accept_ra" . "0"))
    ;;          '(("net.ipv6.conf.default.accept_ra" . "0"))
    ;;          '(("net.ipv6.conf.eth0.accept_ra" . "0"))
  #+end_src



**** option-1-static-addr-static-ipv4-gateway-dynamic-ipv6-gateway
**** option-2-static-addr-static-gateway

***  «nftables-service-type»
#+begin_src scheme :noweb-ref nftables-service-type
  ;; Based on the default firewall configuration
  ;; Changing ssh to be only allowed from the
  ;; Spectrum DHCP range that my homelab ip is
  ;; allocated from.
  (service nftables-service-type
	   (nftables-configuration
	    (ruleset (plain-file "nftables.conf"
				 "\
  table inet filter {
    chain input {
      type filter hook input priority filter; policy drop;
      ct state invalid drop
      ct state { established, related } accept
      iif \"lo\" accept
      iif != \"lo\" ip daddr 127.0.0.0/8 drop
      iif != \"lo\" ip6 daddr ::1 drop
      ip protocol icmp accept
      ip6 nexthdr ipv6-icmp accept
      ip saddr 70.123.224.0/19 tcp dport 22 accept
      reject
    }

    chain forward {
      type filter hook forward priority filter; policy drop;
    }

    chain output {
      type filter hook output priority filter; policy accept;
    }
  }"))))
#+end_src
*** «openssh-service-type»
Configure SSH to...
- [[(ssh-public-key-only)]]: Prohibit all password logins
- [[(ssh-permit-root-login)]]: Allow root to login via my ssh key
#+begin_src scheme :noweb-ref openssh-service-type
  ;; Configure SSH
  (service openssh-service-type
	   (openssh-configuration
	    (password-authentication? #f)           ; (ref:ssh-public-key-only)
	    (public-key-authentication? #t)
	    (permit-root-login 'prohibit-password)  ; (ref:ssh-permit-root-login)
	    (authorized-keys
	     `(("root",
		(plain-file "id-2025-whk-development-ed25519.pub"
			    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO8R7fnSOC91BZgrOPchusXT9faa4dsbKUmL/ZvTQp/F WHK (develop@whk.name) Development Key"))))))
#+end_src
*** «guix-service»
Change the configuration for [[https://guix.gnu.org/manual/en/html_node/Base-Services.html#index-guix_002dservice_002dtype][guix-service-type]] which controls the environment
for guix-daemon which affects runs of ~guix system reconfigure~.
#+begin_src scheme :noweb no-export :noweb-ref guix-service
  (guix-service-type
   config =>
   (guix-configuration
    (inherit config)
    «use-current-guix-version-on-install»
    «change-substitutes»))
#+end_src
**** «use-current-guix-version-on-install»
Use the current version of guix rather than an earlier snapshot^{[[ref-07]]}.
#+begin_src scheme :noweb-ref use-current-guix-version-on-install
  ;; Install and run the current Guix
  ;; rather than an older snapshot.
  (guix (current-guix))
#+end_src
**** «change-substitutes»
Due to [[*TCP issues - 2025-12][TCP issues - 2025-12]] I cannot currently reach mirrors that only
support TCP ipv4.  So currently just using bordeaux which has an ipv6 address.
#+begin_src scheme :noweb-ref change-substitutes
  ;; Add mirror and change order of official substitute servers
  (substitute-urls 
   '(
     ;; "https://bordeaux-us-east-mirror.cbaines.net" ; (ref:bordeaux-us-east-mirror)
     "https://bordeaux.guix.gnu.org"
     ;;"https://ci.guix.gnu.org"
    ))
#+end_src
- [[(bordeaux-us-east-mirror)]]: U.S. mirror of bordeaux^{[[ref-08]]}.
*** Final version
#+INCLUDE: "tangle/guix-minimal-config.scm" src scheme

** Transfer files
From dev side transfer ~guix-minimal-config.scm~ tangled from this file.

#+begin_example bash
  scp guix-minimal-config.scm uman001.erpetu.net:/root/
#+end_example


** Install Guix

#+begin_src bash -n -r
  guix --version  
  mkdir /mnt/guix
  mount LABEL=guixRoot /mnt/guix
  mkdir /mnt/guix/boot
  mount LABEL=guixBoot /mnt/guix/boot
  guix system init \
       --substitute-urls="https://bordeaux.guix.gnu.org" \
       guix-minimal-config.scm /mnt/guix 
#+end_src

** Copy guix-minimal-config.scm to new install
#+begin_src bash
  cp -a guix-minimal-config.scm /mnt/guix/etc/guix-minimal-config.scm
#+end_src


** Reboot and verify Guix Installation
  - Root password is *blank* by default.  Should set on first boot
  - This is not integrated into the VPS provided configuration tools so
    no root password reset, sshkey management from VPS side happens.
    TODO: Look into how this is done



* Troubleshooting
** TCP issues - 2025-12
- Original Symptom
  - Could ssh into guix but could not connect to remote servers when
    running  ~guix pull~ and ~guix reconfigure~
- Cause combination of
  - VPS issue with outgoing ipv4 TCP connections but was fine with
    outgoing ipv6 TCP connections
    |      | in   |     |     | out  |     |     |
    |      | icmp | udp | tcp | icmp | udp | tcp |
    |------+------+-----+-----+------+-----+-----|
    | ipv4 | #t   |     | #t  | #t   | #t  | #f  |
    | ipv6 |      |     |     | #t   |     | #t  |
  - VPS dhcp does not set the ipv6 ip 
    - The VPS provided debian install has a static network configuration so
      it isn't affected
    - My initial testing used dhcp for GUIX
  - The ci.guix.gnu.org does not have a ipv6 address but by default it is
    the first checked
    | Server                | ipv4 address | ipv6 address |
    |-----------------------+--------------+--------------|
    | git.guix.gnu.org      | #t           | #t           |
    | codeberg.org          | #t           | #t           |
    | ci.guix.gnu.org       | #t           | #f           |
    | bordeaux.guix.gnu.org | #t           | #t           |
- Resolution
  - INPROGRESS Set Guix install to manual network configuration
  - TODO       Submit ticket to VPS about outgoing TCP ipv4 issues
- General weirdness to investigate
  - Since I had a incoming ipv4 TCP connection I tried to use SSH as
    and http/https proxy and as a sock proxy but I couldn't get
    ~git pull~ to work.   It should have been possible but I couldn't
    figure it out.

- From debian reinstall command for speed:
#+begin_src bash
  dd if=/dev/zero of=/dev/vda3 bs=4096 count=5234427 status=progress && \
      mke2fs -t ext4 -b 4096 -L "guixRoot" /dev/vda3 && \
      mount LABEL=guixRoot /mnt/guix && \
      mkdir /mnt/guix/boot && \
      mount LABEL=guixBoot /mnt/guix/boot && \
      guix system init \
	   --substitute-urls="https://bordeaux.guix.gnu.org" \
	   /root/guix-minimal-config.scm /mnt/guix
#+end_src

* References
1. Joshua Branson, Christopher Lemmer Webber,
     [[https://guix.gnu.org/en/blog/2020/running-guix-system-on-a-linode-server/][Running Guix System on a Linode Server]], 2020-10-06.
     License: [[https://creativecommons.org/licenses/by-sa/4.0/][CC-BY-SA-4.0]] and [[https://www.gnu.org/licenses/fdl-1.3.html][GFDL-1.3-no-invariants-or-later]]
2. guix.gnu.org, [[https://guix.gnu.org/manual/en/html_node/Binary-installation.html][Binary Installation (GNU Guix Reference Manual)]].
    License: [[https://guix.gnu.org/manual/en/html_node/GNU-Free-Documentation-License.html][GFDL-1.3]]. Accessed: 2025-12-13.
3. Rutherther, [[https://lists.gnu.org/archive/html/guix-devel/2025-12/msg00182.html][GNU Guix 1.5.0rc1 available for testing!]],
    [[https://lists.gnu.org/mailman/listinfo/guix-devel][Guix-devel list]], 2025-12-27T10:43:37+01:00.
    Accessed: 2025-12-28
4. <<ref-04>>Simon Josefsson,
    [[https://lists.gnu.org/archive/html/help-guix/2025-12/msg00096.html][Re: GNU Guix 1.5.0rc1 testing: Generated system unable to do guix pull and profiles/per-user/root doesn't have current guix specified]],
    [[https://lists.gnu.org/mailman/listinfo/help-guix][Help-Guix list]], 2025-12-30T11:11:57+01:00. Accessed: 2025-12-30 
5. <<ref-05>>LWN.net, Joe Brockmeier,
   [[https://lwn.net/Articles/1035491/][Removing Guix from Debian]]. License [[https://creativecommons.org/licenses/by-sa/4.0/][CC BY-SA 4.0]]. Accessed 2025-12-13.
6. guix.gnu.org, [[https://guix.gnu.org/manual/en/html_node/Using-the-Configuration-System.html][Using the Configuration System (GNU Guix Reference Manual)]].
   License: [[https://guix.gnu.org/manual/en/html_node/GNU-Free-Documentation-License.html][GFDL-1.3]].
7. <<ref-07>>Rutherther, [[https://lists.gnu.org/archive/html/help-guix/2025-12/msg00094.html][Re: GNU Guix 1.5.0rc1 testing: Generated system unable to do guix pull and profiles/per-user/root doesn't have current guix specified]],
   [[https://lists.gnu.org/mailman/listinfo/help-guix][Help-Guix list]], 2025-12-30T10:17:08+0100. Accessed: 2025-12-30
8. <<ref-08>>FSF libreplanet.org wiki, [[https://libreplanet.org/wiki/Group:Guix/Mirrors][Group: Guix/Mirrors]]. Accessed: 2025-12-30
* File Listings
** ~index.org~
#+BEGIN_details
#+HTML: <summary>The index.org source file for this page</summary>
#+INCLUDE: "index.org" example
#+END_details
