#+SETUPFILE: templates/level-3.org
#+TITLE: Website Generation from org-mode
#+DATE: 2025-03-06
#+AUTHOR: whk (https://whk.name/about/me)
#+EMAIL: develop@whk.name
#+SUBTITLE:
#+DESCRIPTION: Creates a relocatebable website based on my working notebook
#+KEYWORDS: org-mode web
#+STARTUP: content
* Introduction
:documentMetadata:
#+BEGIN_details
#+HTML:<summary>Document Metadata</summary>
+ Copyright:
  - SPDX-License-Identifier: CC-BY-SA-4.0 or AGPL-3.0-or-later
  - SPDX-FileCopyrightText: © 2025 WHK <develop@whk.name>
  - See {{{insertRelativeLink(about/licensing/index.org,Licensing)}}} for more details
+ Author: {{{author}}}
+ Created: {{{date}}}
+ Changes
  - 2025-03-02: Created
#+END_details
:END:

References:
- [[https://orgmode.org/manual/Publishing.html][Publishing (The Org Manual)]]
- [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Publishing Org-mode files to HTML]]

Configuration used to generate the whk.name website using ~org-publish-project~ 

** Design Considerations
*** RELOCATABLE
Resultant website should be relocatable with no internal absolute URLs.
This allows it to be hosted on my domain, IPFS, localfile, etc.
*** REPRODUCABLE
A complete rebuild of the site where nothing has changed
should always be a [[https://reproducible-builds.org/][Reproducible Build]].  If something was changed
only files dependent on that change should be different.
*** MINIMIZEMETAEFFORT
This should be foremost a working development notebook.  The overhead
when working with my notes to allow them to be used for a
functional website should be minimized as much as possible.

- Web site metadata and structure

  The [[Thunar template][default file template]] should contain all repetitive default
  information needed for the page.

  The selection of the correct =level-#= [[Templates][template]] should set everything
  required to have the web site be [[RELOCATABLE][relocatable]].  This includes defining
  the =insertReleativeLink= macro to allow cross document links to
  just work.

- Licensing

  Collect any explanations for licensing decisions in
  {{{insertRelativeLink(about/licensing/index.org,Licensing)}}} file.
  So it only has to be written once.

  Put my prefered (default) licensing terms and SPDX data
  into the [[Thunar template][default file template]].

  Use {{{insertRelativeLink(notebook/cookbook/fsfe-reuse/index.org,FSFE's reuse)}}} to
  quickly lint the project as I work.  I am not going for complete compliance
  but rather making sure I am not making major errors.

  Define macro's to allow (relatively) easy, clear, and fsfe-ruse compliant
  marking of CC0-1.0 snippets.

*** SELFCONTAINED
Any dependent css, js and other files needed to use the final website
should be hosted with the website.

*** FREE
The resultant website should be free as in freedom.  Anybody who accesses the
site should...

- have everything they need to reproduce the contents of the site.

  - The source repository should be included at the same location
  - The tools needed to build the site should be Opensource
    and readily available.  The build process should be clearly documented
    (this file).
    
- have the permissions needed to modify and share any content on
  the site.

  See {{{insertRelativeLink(about/licensing/index.org,Licensing)}}} for details.

- be able to view through the website the source files that created each
  page.

  Currently implemented by including the [[File Listings][file listings]] at the end of
  each document.  But this is an incomplete and stopgap kludge.

  I would like the final solution to be a javascript git browser that
  can provide a view to the included git repositories and then provide
  a link to them.

** Issues
- ~.org~ to ~.html~ rewrite during export
  
  Normally this is what I want.  But it doesn't support the case where I want to
  point to an actually org file in the final website.   The normal solution is
  to use ~http~ links but they require an absolute URL which violates [[RELOCATABLE][RELOCATABLE]]

  Current workaround is to use ~INCLUDEFILE~ instead.  This bloats the resultant
  web page some but ~\_(ツ)_/~. 

  #+begin_src org
    ,#+BEGIN_details
    ,#+HTML: <summary>The index.org source file for this page</summary>
    ,#+INCLUDE: "index.org" example org
    ,#+END_details
  #+end_src

* Build the website

Autogenerates index.el from the emacs-lisp src blocks in this
file and then runs it inside emacs.

TODO: Consider moving to [[https://github.com/tgbugs/orgstrap/blob/master/README.org][Orgstrap: Executable Org files]]

** ~build-website.sh~

#+NAME: build-website.sh
#+HEADER: :tangle   "build-website.sh"
#+HEADER: :shebang  "#!/usr/bin/bash"
#+HEADER: :noweb    yes
#+HEADER: :comments noweb
#+HEADER: :mkdirp   yes
#+begin_src bash
  # Get location where script is running
  #  Ref: https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
  SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

  # Run the file
  emacs --batch --load="~/.emacs.d/init.el" \
	--eval "(org-babel-load-file \"${SCRIPT_DIR}/index.org\")"
#+end_src
** ~index.el~
#+NAME: index.el
#+HEADER: :tangle "index.el"
#+HEADER: :noweb no-export
#+HEADER: :comments none
#+begin_src emacs-lisp
  (setq org-publish-project-alist
	'(
	  «notebookProject»
	  «aboutProject»
	  «dotfilesProject»
	  «emacs.dProject»
	  )
	)
  (org-publish "notebook")
  (org-publish "about")
  (org-publish "dotfiles-hmtl")
  (org-publish "emacs.d-html")
#+end_src

* Org Publish Project Descriptions
** notebook
Working Notebook

*** ~«notebookProject»~
#+NAME: notebookProject
#+HEADER: :tangle no
#+HEADER: :noweb no-export
#+begin_src emacs-lisp
  ("notebook-html"
   «project-html-global»
   «notebookCommon»
   ;; :auto-sitemap t
   :auto-index t
   :index-filename "sitemap.org"
   )
  ("notebook-static"
   «notebookCommon»
   :base-extension "org\\|el\\|sh\\|css\\|js\\|png"
   :publishing-function org-publish-attachment
   )
  ("notebook" :components ("notebook-html"
			   "notebook-static"
			   ))
#+end_src

*** ~«notebookCommon»~
The Common settings for the notebook

- While working on merge ignore everything in the ~toBeIntegrated~ directory

#+NAME: notebookCommon
  #+HEADER: :tangle no
  #+begin_src emacs-lisp
  :base-directory "../.."
  :publishing-directory "~/build/web/notebook/"
  :recursive t
  :exclude "toBeIntegrated/.*\\|config/publish/about/.*"
  #+end_src

** ~«aboutProject»~
The top level about pages

#+NAME: aboutProject
#+HEADER: :tangle no
#+HEADER: :noweb no-export
#+begin_src emacs-lisp
  ("about-html"
   «project-html-global»
   :base-directory "./about"
   :publishing-directory "~/build/web/about/"
   :recursive t
   )
  ("about-static"
   :base-directory "./about"
   :publishing-directory "~/build/web/about/"
   :recursive t
   :base-extension "org\\|el\\|sh\\|css\\|js\\|png\\|asc\\|bib\\|csl\\|xml"
   :publishing-function org-publish-attachment
   )
  ("about" :components ("about-html"
			"about-static"
			))
#+end_src
  


** ~«dotfilesProject»~
Personal Dotfile configuration

#+NAME: dotfilesProject
#+HEADER: :tangle no
#+HEADER: :noweb no-export
#+begin_src emacs-lisp
  ("dotfiles-html"
   «project-html-global»
   :base-directory "~/dotfiles/"
   :publishing-directory "~/build/web/misc/dotfiles/"
   :recursive f
   ;; «template-level-2»
   )
#+end_src
** ~«emacs.dProject»~
#+NAME: emacs.dProject
#+HEADER: :tangle no
#+HEADER: :noweb no-export
#+begin_src emacs-lisp
  ("emacs.d-html"
   «project-html-global»
   :base-directory "~/.emacs.d/"
   :publishing-directory "~/build/web/misc/emacs.d/"
   :recursive f
   )
#+end_src



** global settings - ~«project-html-global»~
Settings used by all org html exporters.
- Turn off ~section-numbers~

  Partly for aesthetics but mostly so plain ~[[orglinks]]~ don't get
  converted into #.#.# output.
- Turn off ~with-timestamps~ and ~time-stamp-file~

  Putting the build timestamp inside the file violates [[REPRODUCABLE]]

  As far as I can tell from [[https://orgmode.org/manual/Publishing-options.html#Generic-properties-1][Publishing Options - Generic properties]]
  just turning off ~with-timestamps~ should prevent this but at this time
  does not.  The code in [[https://github.com/emacsmirror/org/blob/62a8677e4c479d3ff5364b9141770bd4922a0fe0/lisp/ox-html.el#L1977][org/lisp/ox-html.el@1977]] checks ~time-stamp-file~.
  
  TODO: Determine if this is operator error, documentation bug, or a real bug.

- Enable =html_use_infojs=
  - See [[file:third-party/index.org::org-info-src.js][Third Part Files used in website generation]] for details
  - The embeded javascript code is licensed [[https://spdx.org/licenses/GPL-3.0-or-later.html][GPL-3.0-or-later]]
    
#+NAME: project-html-global
#+HEADER: :tangle no
#+begin_src emacs-lisp
  :base-extension "org"
  :publishing-function org-html-publish-to-html
  :section-numbers t
  :with-timestamps nil
  :time-stamp-file nil
  :html-use-infojs t
  :html-home/up-format ""
;;  :html-infojs-options (
;;			(path . "https://orgmode.org/org-info.js")
;;			(view . "info")
;;			(toc . :with-toc)
;;			(ftoc . "0")
;;			(tdepth . "max")
;;			(sdepth . "max")
;;			(mouse . "underline")
;;			(buttons . nil)
;;			(ltoc . "above")
;;			(up . :html-link-up)
;;			(home . :html-link-home))
  :html-allow-name-attribute-in-anchors t
  :html-prefer-user-labels t
#+end_src

* Templates
Handle HTML settings for each relative level in the output.
- ~level-#.org~ are templates that can be added to the top of an org file
  using ~#SETUPFILE~.
  - =html_link_home= : Set to reach the top of the website
  - =html_link_up=   : At level 0 points to itself.  All others points up a level.
  - Macro =insertRelativeLink= : Creates a link to a document relative current position


** ~level-0.org~
#+NAME: level-0.org
#+HEADER: :tangle "templates/level-0.org"
#+HEADER: :mkdirp yes
#+HEADER: :noweb no-export
#+begin_src org
  «levelCommon»
  ,#+html_link_home: .
  ,#+html_link_up:   .
  ,#+INFOJS_OPT: path:notebook/config/publish/third-party/org-info-src.js ltoc:above
  ,#+MACRO: insertRelativeLink (eval (concat "[[" $1 "][" $2 "]]")) ; $1-link $2 - text
#+end_src

** ~level-1.org~
#+NAME: level-1.org
#+HEADER: :tangle "templates/level-1.org"
#+HEADER: :mkdirp yes
#+HEADER: :noweb no-export
#+begin_src org
  «levelCommon»
  ,#+html_link_home: ..
  ,#+html_link_up:   ..
  ,#+INFOJS_OPT: path:../notebook/config/publish/third-party/org-info-src.js ltoc:above
  ,#+MACRO: insertRelativeLink (eval (concat "[[../" $1 "][" $2 "]]")) ; $1-link $2 - text
#+end_src
** ~level-2.org~
#+NAME: level-2.org
#+HEADER: :tangle "templates/level-2.org"
#+HEADER: :mkdirp yes
#+HEADER: :noweb no-export
#+begin_src org
  «levelCommon»
  ,#+html_link_home: ../..
  ,#+html_link_up:   ..
  ,#+INFOJS_OPT: path:../../notebook/config/publish/third-party/org-info-src.js ltoc:above
  ,#+MACRO: insertRelativeLink (eval (concat "[[../../" $1 "][" $2 "]]")) ; $1-link $2 - text
#+end_src
** ~level-3.org~
#+NAME: level-3.org
#+HEADER: :tangle "templates/level-3.org"
#+HEADER: :mkdirp yes
#+HEADER: :noweb no-export
#+begin_src org
  «levelCommon»
  ,#+html_link_home: ../../..
  ,#+html_link_up:   ..
  ,#+INFOJS_OPT: path:../../../notebook/config/publish/third-party/org-info-src.js ltoc:above
  ,#+MACRO: insertRelativeLink (eval (concat "[[../../../" $1 "][" $2 "]]")) ; $1-link $2 - text
#+end_src
** ~level-4.org~
#+NAME: level-4.org
#+HEADER: :tangle "templates/level-4.org"
#+HEADER: :mkdirp yes
#+HEADER: :noweb no-export
#+begin_src org
  «levelCommon»
  ,#+html_link_home: ../../../..
  ,#+html_link_up:   ..
  ,#+INFOJS_OPT: path:../../../../notebook/config/publish/third-party/org-info-src.js ltoc:above
  ,#+MACRO: insertRelativeLink (eval (concat "[[../../../../" $1 "][" $2 "]]")) ; $1-link $2 - text
 #+end_src
** Common
- Default created using ~C-c C-e # html~ 

- Added:

  These are not in the created default but listed in [[https://orgmode.org/manual/Publishing-options.html][Publishing options]]
  and elsewhere.


- Changes:

   - =html-postamble= : =auto= → =nil=


    Do not automatically generate a footer.
    
    TODO: Merge in my planned footer from old website generation

  - =html-fancy= : =nil= → =t=

    Ref: [[https://orgmode.org/manual/HTML-doctypes.html][HTML doctypes]] discussion of ~html-fancy~
    
    Support the full set of html5 block elements

  - =html_doctype= (=:html-doctype=) : =xhtml-strict= → =html5=

- Removed:

  Since they are set elsewhere or I want to use whatever there default may
  be at the time of generation

  | Header Arg       | Alt Form         | Reason        |
  |------------------+------------------+---------------|
  | =description=    |                  | set per file  |
  | =keywords=       |                  | set per file  |
  | =html_link_home= | =html-link-home= | set per level |
  | =html_link_up=   | =html_link_up=   | set per level |
  | =subtitle=       |                  | set per file  |
  | =create=         |                  | Use default   |

*** ~«levelCommon»~
#+NAME: levelCommon
#+HEADER: tangle no
#+begin_src org
  ,#+options: html-link-use-abs-url:nil
  ,#+options: html-postamble:nil 
  ,#+options: html-preamble:t html-scripts:nil html-style:t
  ,#+options: html5-fancy:t tex:t
  ,#+html_doctype: html5
  ,#+html_container: div
  ,#+html_content_class: content
  ,#+html_mathjax:
  ,#+html_equation_reference_format: \eqref{%s}
  ,#+html_head:
  ,#+html_head_extra:
  ,#+latex_header:
#+end_src


** Thunar template
Template used by thunar when creating a new file
- =~/Templates/index.org=
  #+INCLUDE: "~/Templates/index.org" example org

* File Listings
** ~index.org~
#+BEGIN_details
#+HTML: <summary>The index.org source file for this page</summary>
#+INCLUDE: "index.org" example
#+END_details

** ~build-website.sh~
#+BEGIN_details
#+HTML: <summary>Generated build-website.sh</summary>
#+INCLUDE: "build-website.sh" example
#+END_details

** ~index.el~
#+BEGIN_details
#+HTML: <summary>Generated index.el</summary>
#+INCLUDE: "index.el" example emacs-lisp
#+END_details

** Templates
#+BEGIN_details
#+HTML: <summary>templates/level-0.org</summary>
#+INCLUDE: "templates/level-0.org" example org  
#+END_details
#+BEGIN_details
#+HTML: <summary>templates/level-1.org</summary>
#+INCLUDE: "templates/level-1.org" example org  
#+END_details
#+BEGIN_details
#+HTML: <summary>templates/level-2.org</summary>
#+INCLUDE: "templates/level-2.org" example org  
#+END_details
#+BEGIN_details
#+HTML: <summary>templates/level-3.org</summary>
#+INCLUDE: "templates/level-3.org" example org  
#+END_details






