server.errorlog = "/workingdir/log/http_error.log"
server.name = "whk.name"
server.document-root = "www"
server.port = 8080
server.modules = (
  "mod_expire",
)
mimetype.assign = (
  ".html" => "text/html", 
  ".txt" => "text/plain",
  ".jpg" => "image/jpeg",
  ".png" => "image/png",
  ".gif" => "image/gif",
  ".css" => "text/css" 
)

index-file.names = ( "index.html" )

# We are static let them cache
$HTTP["url"] =~ "^/" {
         expire.url = ( "" => "access plus 8 hours" )
}

# Allow access to git repositories
#$HTTP["url"] =~ "^/src/.*\.git/" {
#    dir-listing.activate = "enable" 
#}
